### ISSUE TITLE
Confused by StoreWatcher

### ISSUE THREAD

**Issue by itsJoKr** [google/flutter_flux#17]
Flutter stateless widgets have build method. That's where you build your widget. Stateful widgets on other hand have createState method, and are delegating build to State class.

What's confusing to me that StoreWatcher is a StatefulWidget, but it has both build and createState methods. As far as I understood it, you can use build when you don't need extra state, so you don't create extra class. But if you need it, you can override createState class and have StoreWatcherState.

So I debugged it, and when you override createState on StoreWatcher, the **build method in StoreWatcher is ignored**, and State class will build a widget. Which is OK, but now you **cannot remove the StoreWatcher build method** because it needs concrete implementation? Am I doing something wrong?

**Comment by jimbeveridge** [comment]
StoreWatcher is a StatefulWidget, but that's an implementation detail that you can ignore. You don't need to do anything special to support the fact that it's a StatefuWidget. All you need to do is implement `initStores()` and a specialized `build()` function in your derived class. The special `build()` function provides a way to access the stores using the store tokens.

For example, in `example/lib/main.dart`, you can see an implementation of this special `build()` function, which starts like this:
```
  @override
  Widget build(BuildContext context, Map<StoreToken, Store> stores) {
    final ChatMessageStore messageStore = stores[messageStoreToken];
    final ChatUserStore chatUserStore = stores[userStoreToken];
```

It sounds like the problem you are seeing is because you are trying to derive from StoreWatcher. Don't do this :-)  StoreWatcher is a convenience class that just demonstrates how to use `StoreWatcherMixin`. So the solution is to mix `StoreWatcherMixin` into your class and implement the same functions used in StoreWatcher. Unfortunately, I haven't had time to write the documentation to demonstrate this.

**Comment by itsJoKr** [comment]
OK, I think I've got it now.

The problem was indeed that I thought `StoreWatcher` is the main class that I should use. That's why I saw limitation in some cases. I can use `StoreWatcherMixin` when I want more flexibility, or `StoreWatcher` for the probably most common case when you just want to rebuild widget based on store.

Thanks for the explanation. Going to close this now.
